# Generated by Django 3.2.3 on 2021-06-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20210603_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='outputproduce',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_time',
            new_name='create_time',
        ),
    ]
