# Generated by Django 3.2.3 on 2021-06-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20210604_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
